# Install generic ubuntu and rails
FROM ruby:3.2.1 AS rails-base

# Install libvips for Active Storage preview support
RUN apt-get update -qq && \
    apt-get install -y build-essential libvips && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

RUN gem update
RUN gem install rails

COPY ./Gemfile ./Gemfile.lock ./
RUN bundle install
RUN rm Gemfile
RUN rm Gemfile.lock

WORKDIR /app