version: '3'
services:
  api:
    container_name: backend
    build: .
    command: sh -c "
      cd /rails &&
      rake db:migrate
      "
    ports:
      - 3000:3000
  postgres:
    image: postgres:13.4
    restart: always
    volumes:
      - ${VOLUME_ROOT}/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: basic_development
    ports:
      - 9432:5432

      #RAILS_ENV=production rake -t db:migrate
      