services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    command: /bin/bash -c "rm -f /tmp/server.pid && bin/rails server -b 0.0.0.0 -P /tmp/server.pid"

  postgres:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5432

volumes:
  postgres:
  bundle_cache:
